Adding missing #include <typeinfo>
  - To correct the following compilation error (happening with g++ 4.9.2):
      Gate/source/general/include/GateMiscFunctions.icc: In function ‘std::vector<_RealType> parse_N_values_of_type_T(std::string, int, const string&)’:
      Gate/source/general/include/GateMiscFunctions.icc:40:69: error: must #include <typeinfo> before using typeid
            << ", expected " << N << " value(s) of type " << typeid(T).name() << std::endl;